apps/article/urls.py
from django.urls import path

from .views import articleDetailView, articleListView

app_name = "article"

urlpatterns = [
    path('detail/<articleID>/', articleDetailView.as_view(), name="articleDetail"),
    path('list/', articleListView.as_view(), name="articleList")
]

autoCN/urls.py
# from django.contrib import admin
from django.urls import path,include

import xadmin
from autoApi.views import RunCaseView,RunPageView,ReturnRateView,reportDetailView,addNotesView,failReportView,dashboardView,caseEditorView,failReasonView,caseListView,JenkinsRunCaseView
from users.views import IndexView,loginView,logoutView

urlpatterns = [
    #path(route,view,name=None,kwargs=None)
    path('xadmin/', xadmin.site.urls),
    # path('admin/', admin.site.urls),
    path('',IndexView.as_view(),name="index"),
    path('dashboard/', dashboardView.as_view(), name="dashboard"),
    path('runPage/',RunPageView.as_view(),name="runPage"),
    path('runCase/',RunCaseView.as_view(),name="runCase"),
    path('jenkinsRunCase/',JenkinsRunCaseView.as_view(),name="jenkinsRunCase"),
    path('returnRate/',ReturnRateView.as_view(),name="returnRate"),
    path('reportDetail/<reportID>/',reportDetailView.as_view(),name="reportDetail"),
    path('login/',loginView.as_view(),name="login"),
    path('logout/',logoutView.as_view(),name="logout"),
    path('addNotes/<noteID>/',addNotesView.as_view(),name="addNotes"),
    path('failReport/<department>/<env>',failReportView.as_view(),name="failReport"),
    path('caseEditor/',caseEditorView.as_view(),name="caseEditor"),
    path('failReason/',failReasonView.as_view(),name="failReason"),
    path('caseList/',caseListView.as_view(),name="caseList"),
    path('article/',include("article.urls",namespace="article")),
]

handler404='users.views.page_not_found'
handler500='users.views.page_error'

extra_apps/DjangoUeditor/urls.py
# coding:utf-8
from django import VERSION
from .widgets import UEditorWidget, AdminUEditorWidget
from .views import get_ueditor_controller
from django.conf.urls import url

urlpatterns = [
    url(r'^controller/$', get_ueditor_controller),
]

extra_apps/xadmin/views/base.py
import copy
import functools
import datetime
import decimal
from functools import update_wrapper
from inspect import getfullargspec

from django import forms
from django.apps import apps
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import get_permission_codename
from django.core.exceptions import ValidationError
from django.core.serializers.json import DjangoJSONEncoder
from django.urls.base import reverse
from django.http import HttpResponse
from django.template import Context, Template
from django.template.response import TemplateResponse
from django.utils import six
from django.utils.decorators import method_decorator, classonlymethod
from django.utils.encoding import force_text, smart_text, smart_str
from django.utils.functional import Promise
from django.utils.http import urlencode
from django.utils.itercompat import is_iterable
from django.utils.safestring import mark_safe
from django.utils.text import capfirst
from django.utils.translation import ugettext as _
from django.views.decorators.csrf import csrf_protect
from django.views.generic import View
from collections import OrderedDict
from xadmin.util import static, json, vendor, sortkeypicker

from xadmin.models import Log

csrf_protect_m = method_decorator(csrf_protect)


class IncorrectPluginArg(Exception):
    pass


def get_content_type_for_model(obj):
    from django.contrib.contenttypes.models import ContentType
    return ContentType.objects.get_for_model(obj, for_concrete_model=False)


def filter_chain(filters, token, func, *args, **kwargs):
    if token == -1:
        return func()
    else:
        def _inner_method():
            fm = filters[token]
            fargs = getfullargspec(fm)[0]
            if len(fargs) == 1:
                # Only self arg
                result = func()
                if result is None:
                    return fm()
                else:
                    raise IncorrectPluginArg(u'Plugin filter method need a arg to receive parent method result.')
            else:
                return fm(func if fargs[1] == '__' else func(), *args, **kwargs)
        return filter_chain(filters, token - 1, _inner_method, *args, **kwargs)


def filter_hook(func):
    tag = func.__name__
    func.__doc__ = "``filter_hook``\n\n" + (func.__doc__ or "")

    @functools.wraps(func)
    def method(self, *args, **kwargs):

        def _inner_method():
            return func(self, *args, **kwargs)

        if self.plugins:
            filters = [(getattr(getattr(p, tag), 'priority', 10), getattr(p, tag))
                       for p in self.plugins if callable(getattr(p, tag, None))]
            filters = [f for p, f in sorted(filters, key=lambda x:x[0])]
            return filter_chain(filters, len(filters) - 1, _inner_method, *args, **kwargs)
        else:
            return _inner_method()
    return method


def inclusion_tag(file_name, context_class=Context, takes_context=False):
    def wrap(func):
        @functools.wraps(func)
        def method(self, context, nodes, *arg, **kwargs):
            _dict = func(self, context, nodes, *arg, **kwargs)
            from django.template.loader import get_template, select_template
            cls_str = str if six.PY3 else basestring
            if isinstance(file_name, Template):
                t = file_name
            elif not isinstance(file_name, cls_str) and is_iterable(file_name):
                t = select_template(file_name)
            else:
                t = get_template(file_name)

            _dict['autoescape'] = context.autoescape
            _dict['use_l10n'] = context.use_l10n
            _dict['use_tz'] = context.use_tz
            _dict['admin_view'] = context['admin_view']

            csrf_token = context.get('csrf_token', None)
            if csrf_token is not None:
                _dict['csrf_token'] = csrf_token
            nodes.append(t.render(_dict))

        return method
    return wrap


class JSONEncoder(DjangoJSONEncoder):

    def default(self, o):
        if isinstance(o, datetime.datetime):
            return o.strftime('%Y-%m-%d %H:%M:%S')
        elif isinstance(o, datetime.date):
            return o.strftime('%Y-%m-%d')
        elif isinstance(o, decimal.Decimal):
            return str(o)
        elif isinstance(o, Promise):
            return force_text(o)
        else:
            try:
                return super(JSONEncoder, self).default(o)
            except Exception:
                return smart_text(o)


class BaseAdminObject(object):

    def get_view(self, view_class, option_class=None, *args, **kwargs):
        opts = kwargs.pop('opts', {})
        return self.admin_site.get_view_class(view_class, option_class, **opts)(self.request, *args, **kwargs)

    def get_model_view(self, view_class, model, *args, **kwargs):
        return self.get_view(view_class, self.admin_site._registry.get(model), *args, **kwargs)

    def get_admin_url(self, name, *args, **kwargs):
        return reverse('%s:%s' % (self.admin_site.app_name, name), args=args, kwargs=kwargs)

    def get_model_url(self, model, name, *args, **kwargs):
        return reverse(
            '%s:%s_%s_%s' % (self.admin_site.app_name, model._meta.app_label,
                             model._meta.model_name, name),
            args=args, kwargs=kwargs, current_app=self.admin_site.name)

    def get_model_perm(self, model, name):
        return '%s.%s_%s' % (model._meta.app_label, name, model._meta.model_name)

    def has_model_perm(self, model, name, user=None):
        user = user or self.user
        return user.has_perm(self.get_model_perm(model, name)) or (name == 'view' and self.has_model_perm(model, 'change', user))

    def get_query_string(self, new_params=None, remove=None):
        if new_params is None:
            new_params = {}
        if remove is None:
            remove = []
        p = dict(self.request.GET.items()).copy()
        arr_keys = list(p.keys())
        for r in remove:
            for k in arr_keys:
                if k.startswith(r):
                    del p[k]
        for k, v in new_params.items():
            if v is None:
                if k in p:
                    del p[k]
            else:
                p[k] = v
        return '?%s' % urlencode(p)

    def get_form_params(self, new_params=None, remove=None):
        if new_params is None:
            new_params = {}
        if remove is None:
            remove = []
        p = dict(self.request.GET.items()).copy()
        arr_keys = list(p.keys())
        for r in remove:
            for k in arr_keys:
                if k.startswith(r):
                    del p[k]
        for k, v in new_params.items():
            if v is None:
                if k in p:
                    del p[k]
            else:
                p[k] = v
        return mark_safe(''.join(
            '<input type="hidden" name="%s" value="%s"/>' % (k, v) for k, v in p.items() if v))

    def render_response(self, content, response_type='json'):
        if response_type == 'json':
            response = HttpResponse(content_type="application/json; charset=UTF-8")
            response.write(
                json.dumps(content, cls=JSONEncoder, ensure_ascii=False))
            return response
        return HttpResponse(content)

    def template_response(self, template, context):
        return TemplateResponse(self.request, template, context)

    def message_user(self, message, level='info'):
        """
        Send a message to the user. The default implementation
        posts a message using the django.contrib.messages backend.
        """
        if hasattr(messages, level) and callable(getattr(messages, level)):
            getattr(messages, level)(self.request, message)

    def static(self, path):
        return static(path)

    def vendor(self, *tags):
        return vendor(*tags)

    def log(self, flag, message, obj=None):
        log = Log(
            user=self.user,
            ip_addr=self.request.META['REMOTE_ADDR'],
            action_flag=flag,
            message=message
        )
        if obj:
            log.content_type = get_content_type_for_model(obj)
            log.object_id = obj.pk
            log.object_repr = force_text(obj)
        log.save()


class BaseAdminPlugin(BaseAdminObject):

    def __init__(self, admin_view):
        self.admin_view = admin_view
        self.admin_site = admin_view.admin_site

        if hasattr(admin_view, 'model'):
            self.model = admin_view.model
            self.opts = admin_view.model._meta

    def init_request(self, *args, **kwargs):
        pass


class BaseAdminView(BaseAdminObject, View):
    """ Base Admin view, support some comm attrs."""

    base_template = 'xadmin/base.html'
    need_site_permission = True

    def __init__(self, request, *args, **kwargs):
        self.request = request
        self.request_method = request.method.lower()
        self.user = request.user

        self.base_plugins = [p(self) for p in getattr(self,
                                                      "plugin_classes", [])]

        self.args = args
        self.kwargs = kwargs
        self.init_plugin(*args, **kwargs)
        self.init_request(*args, **kwargs)

    @classonlymethod
    def as_view(cls):
        def view(request, *args, **kwargs):
            self = cls(request, *args, **kwargs)

            if hasattr(self, 'get') and not hasattr(self, 'head'):
                self.head = self.get

            if self.request_method in self.http_method_names:
                handler = getattr(
                    self, self.request_method, self.http_method_not_allowed)
            else:
                handler = self.http_method_not_allowed

            return handler(request, *args, **kwargs)

        # take name and docstring from class
        update_wrapper(view, cls, updated=())
        view.need_site_permission = cls.need_site_permission

        return view

templates/Analysis.html
{% extends 'base.html' %}
{% block title %}autoCN自动化接口平台-首頁{% endblock %}
{% load staticfiles %}
{% block content %}

{% endblock %}

templates/articleList.html
{% extends 'base.html' %}
{% block title %}autoCN自动化接口平台-文章详情{% endblock %}
{% load staticfiles %}

{% block content %}
    <table class="table table-striped">
        <tr>
            <td>ID</td>
            <td>标题</td>
            <td>作者</td>
            <td>发布时间</td>
            <td>操作</td>
        </tr>
        {% for article in articleList %}
            <tr>
                <td>{{ article.id }}</td>
                <td><a href="../detail/{{ article.id }}?department={{ department }}&project={{ project }}">{{ article.articleName }}</a></td>
                <td>{{ article.author }}</td>
                <td>{{ article.add_time}}</td>
                <td><a href="#">编辑</a></td>
            </tr>
        {% endfor %}

    </table>



{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="zh-CN">
{% load static %}
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">
    {% block custom_css %}{% endblock %}
    <title>{% block title %}autoCN自动化接口平台{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    {#    <link href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">#}
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/github-markdown-css/2.10.0/github-markdown.min.css"
          rel="stylesheet">
    {% comment %}{% endcomment %}

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="{% static 'css/ie10-viewport-bug-workaround.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/dashboard.css' %}" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="{% static 'js/ie-emulation-modes-warning.js' %}"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://cdn.bootcss.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script>window.jQuery || document.write('<script src="{% static 'js/jquery.min.js' %}"><\/script>')</script>
    <script type="text/javascript" src="{% static 'js/echarts.min.js' %}"></script>

</head>

<body>

<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">autoCN接口自动化测试平台</a>

        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
                <li><a href="#">{% if request.user.is_authenticated %}你好,
                    {{ request.user.username }}</a></li>
                    <li><a href="/logout">登出</a></li>
                {% else %}
                    <li><a href="/login">登录</a></li>
                {% endif %}
            </ul>
            <form class="navbar-form navbar-right">
                <input type="text" class="form-control" placeholder="Search...">
            </form>
        </div>
    </div>
</nav>

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
            <ul class="nav nav-sidebar">
                {% block menu %}
                    <li {% if request.path == '/' %}class="active" {% endif %}><a href="{% url 'index' %}">首页</a></li>
                    <li {% if request.path|slice:'10' == '/dashboard' %}class="active" {% endif %}><a
                            href="{% url 'dashboard' %}?department={{ department }}&project={{ project }}">看板</a></li>
                    <li {% if request.path|slice:'8' == '/runPage' %}class="active" {% endif %}><a
                            href="{% url 'runPage' %}?department={{ department }}&project={{ project }}">执行测试</a></li>
                    <li {% if request.path|slice:'11' == '/failReason' %}class="active" {% endif %}><a
                            href="{% url 'failReason' %}?department={{ department }}&project={{ project }}">失败分析</a>
                    </li>
                    <li {% if request.path|slice:'9' == '/caseList' %}class="active" {% endif %}><a
                            href="{% url 'caseList' %}?department={{ department }}&project={{ project }}">用例列表</a></li>
                    {#                    <li {% if request.path|slice:'12' == '/article/list/' %}class="active" {% endif %}><a href="{% url 'article:articleList' %}?department={{ department }}&project={{ project }}">文章列表</a></li>#}

                {% endblock %}

            </ul>

        </div>

        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
            {% block content %}
            {% endblock %}
        </div>
    </div>
</div>

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<!-- Just to make our placeholder images work. Don't actually copy the next line! -->
<script src="{% static 'js/holder.min.js' %}"></script>
<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<script src="{% static 'js/ie10-viewport-bug-workaround.js' %}"></script>

{% block custom_js %}{% endblock %}

</body>
</html>

templates/caseEditor.html
{% extends 'base.html' %}
{% block title %}autoCN自动化接口平台-用例编辑{% endblock %}
{% load staticfiles %}

{% block content %}
    <div class="container text-center">

        <form class="form-caseEditor" method="post">
            <h2 class="form-signin-heading">测试用例编辑 - {{ casePath }}</h2>
            <h2 class="form-signin-heading">{{ status_code }}</h2>
            <textarea rows="50" cols="150" name="caseDetail" id="caseDetail">{{ caseDetail }}</textarea>
            <button class="btn btn-lg btn-primary btn-block" type="submit">保存</button>
            {% csrf_token %}
        </form>

    </div> <!-- /container -->




{% endblock %}

templates/caseList.html
{% extends 'base.html' %}
{% block title %}autoCN自动化接口平台-用例编辑{% endblock %}
{% load staticfiles %}

{% block content %}
    <h2 class="form-signin-heading">{{ project.projectName }}-测试用例列表</h2>
    <div class="dropdown text-left">
        <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown"
                aria-haspopup="true" aria-expanded="true" style="width: 150px">
            {% if project.projectName != None %}
                {{ project.projectName }}
            {% else %}
                未选择
            {% endif %}
            <span class="caret"></span>
        </button>
        <ul class="dropdown-menu" aria-labelledby="dropdownMenu1" style="width: 150px">
            {% for project in projectList %}
                <li><a href="./?department={{ department }}&project={{ project }}">{{ project.projectName }}</a></li>
                <li role="separator" class="divider"></li>
            {% empty %}
                <li>None</li>
            {% endfor %}

        </ul>
    </div>
    <table class="table table-striped">
        <tr>
            <td>文件名</td>
            <td>文件路径</td>
            <td>操作</td>
            <td>执行</td>
        </tr>
        {% for file in fileList %}
            <tr>
                <td>{{ file.fileName }}</td>
                <td>{{ file.filePath }}</td>
                <td>
                    <a href="../caseEditor/?casePath={{ file.filePath }}&department={{ department }}&project={{ project }}">编辑</a>
                </td>
                <td>运行</td>
            </tr>
        {% endfor %}

    </table>


{% endblock %}

templates/errorPage.html
{% extends 'base.html' %}

{% block title %}errorPage{% endblock %}
{% load staticfiles %}

{% block content %}
    <div class="container text-center">
        <h2 class="form-signin-heading">{{ message }}</h2>
    </div> <!-- /container -->

{% endblock %}

templates/failReason.html
{% extends 'base.html' %}
{% block title %}autoCN自动化接口平台-失败原因汇总{% endblock %}
{% load staticfiles %}

{% block content %}
    <h1 class="page-header">{{ project.projectName }}-失败原因分析</h1>
    <div class="dropdown text-left">
        <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown"
                aria-haspopup="true" aria-expanded="true" style="width: 150px">
                {{ env.envName }}
            <span class="caret"></span>
        </button>
        <ul class="dropdown-menu" aria-labelledby="dropdownMenu1" style="width: 150px">
            {% for env in envList %}
                <li><a href="./?department={{ department }}&&project={{ project }}&env={{ env }}">{{ env.envName }}</a></li>
            {% endfor %}

{#            <li role="separator" class="divider"></li>#}
{#            <li><a href="#">其它</a></li>#}
        </ul>
    </div>
    <div class="row" id="tab2" style="height: auto; width: auto">
        <div style="height: 410px;min-height: 100px;width:50%;margin: 0 auto" id="failReportchart" class="col-md-6">
            <script type="text/javascript">
                var mychart = echarts.init(document.getElementById("failReportchart"), 'macarons');
                option = {
                    title: {
                        text: '执行失败原因分析',
                        subtext: '接口自动化',
                        x: 'center'
                    },
                    tooltip: {
                        trigger: 'item',
                        formatter: "{a} <br/>{b} : {c} ({d}%)"
                    },
                    series: [
                        {
                            name: '暂无数据',
                            type: 'pie',
                            radius: '55%',
                            center: ['50%', '60%'],
                            data: [
                                {value: 335, name: '暂无数据'},

                            ]
                        }
                    ]
                };
                mychart.showLoading();
                var reasonresult = [];
                $.ajax({
                    type: "get",
                    async: true,
                    url: "/failReport/{{ department }}/{{ env }}",
                    data: {},
                    dataType: "json",
                    success: function (result) {
                        if (result != null && result.length > 0) {
                            for (var i = 0; i < result.length; i++) {
                                if (result[i].resultNum >= 1) {
                                    reasonresult.push({name: result[i].notesCategory, value: result[i].resultNum});
                                }
                            }
                            mychart.hideLoading();
                            mychart.setOption({
                                legend: {
                                    orient: 'vertical',
                                    x: 'left',
                                    data: ['直接访问']
                                },
                                series: [{
                                    name: '通过率',
                                    data: reasonresult,
                                    type: 'pie',
                                    radius: '55%',
                                    areaStyle: {},
                                    center: ['50%', '60%'],
                                }],
                                toolbox: {
                                    show: true,
                                    feature: {
                                        mark: {show: true},
                                        dataView: {show: true, readOnly: false},
                                        magicType: {
                                            show: true,
                                            type: ['pie', 'funnel'],
                                            option: {
                                                funnel: {
                                                    x: '25%',
                                                    width: '50%',
                                                    funnelAlign: 'left',
                                                    max: 1548
                                                }
                                            }
                                        },
                                        restore: {show: true},
                                        saveAsImage: {show: true}
                                    }
                                },
                                calculable: true,


                            })
                        }

                    }
                })
                mychart.setOption(option);
            </script>
        </div>
        <div class="table-responsive col-md-6" style="height: 410px;min-height: 100px;width:50%;margin: 0 auto">
            {#                <h2 class="sub-header" style="width:50%;margin: 0 auto" >Section title</h2>#}
            <table class="table table-striped">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>测试环境</th>
                    <th>通过率</th>
                    <th>执行平台</th>
                    <th>失败原因</th>
                </tr>
                </thead>
                <tbody>
                {% for FailResult in allFailResultList %}
                    <tr>
                        <td>{{ FailResult.id }}</td>
                        <td>{{ FailResult.env }}</td>
                        <td>{% widthratio FailResult.passrate 1 100 %}%</td>
                        <td>{{ FailResult.platform }}</td>
                        <td>{{ FailResult.notesCategory }}</td>


                    </tr>
                {% endfor %}
                <script type="text/javascript">
                    function addNotes(resultid) {
                        $.ajax({
                            type: "POST",
                            dataType: "json",
                            url: "/addNotes/" + resultid + "/",
                            data: {
                                'notes': $('#notesID' + resultid).val(),
                                'notesCategory': $('#notesCategoryID' + resultid).val()
                            },
                            success: function (data) {
                                alert("success!");
                                setTimeout(function () {
                                    location.reload();
                                }, 500)
                            },
                            error: function () {
                                alert("error!");
                            }
                        });
                    }
                </script>
                </tbody>
            </table>
        </div>
    </div>

    <hr>
    <div class="table-responsive col-md-12" style="height: 410px;min-height: 100px;width:100%;margin: 0 auto">
        {#                <h2 class="sub-header" style="width:50%;margin: 0 auto" >Section title</h2>#}
        <table class="table table-striped">
            <thead>
            <tr>
                <th>月份</th>
                <th>模块</th>
                <th>失败数</th>
                <th>总数</th>
                <th>成功率</th>
            </tr>
            </thead>
            <tbody>
            {% for Analysis in AnalysisList %}
                <tr>
                    <td>{{ nowYear }}-{{ nowMonth }}</td>
                    <td>{{ Analysis.0 }}</td>
                    <td>{{ Analysis.2 }}</td>
                    <td>{{ Analysis.1 }}</td>
                    <td>{% widthratio Analysis.2 Analysis.1 100 %}%</td>

                </tr>
            {% endfor %}
            <script type="text/javascript">
                function addNotes(resultid) {
                    $.ajax({
                        type: "POST",
                        dataType: "json",
                        url: "/addNotes/" + resultid + "/",
                        data: {
                            'notes': $('#notesID' + resultid).val(),
                            'notesCategory': $('#notesCategoryID' + resultid).val()
                        },
                        success: function (data) {
                            alert("success!");
                            setTimeout(function () {
                                location.reload();
                            }, 500)
                        },
                        error: function () {
                            alert("error!");
                        }
                    });
                }
            </script>
            </tbody>
        </table>
    </div>
{% endblock %}

templates/view_report.html
{#{% extends 'base.html' %}#}
{#{% block title %}autoCN自动化接口平台-首頁{% endblock %}#}
{#{% load staticfiles %}#}
{#{% block content %}#}
    {{ detail }}
{#{% endblock %}#}